int led = 13;
int led_1 = 12;
int led_2 = 11;
int led_3 = 10;
int led_4 = 9;
int led_5 = 8;
int btn = 7;
int i=0;

void setup() {
  pinMode(led,OUTPUT);
  pinMode(led_1,OUTPUT);
  pinMode(led_2,OUTPUT);
  pinMode(led_3,OUTPUT);
  pinMode(led_4,OUTPUT);
  pinMode(led_5,OUTPUT);
  pinMode(btn,INPUT);
  
}

void loop() {
  if(digitalRead(btn)==HIGH){
    i++;
    delay(500);
  }
  if(i>32){
    i=0;
  }
  if(i==0){
    digitalWrite(led,LOW);
    digitalWrite(led_1,LOW);
    digitalWrite(led_2,LOW);
    digitalWrite(led_3,LOW);
    digitalWrite(led_4,LOW);
    digitalWrite(led_5,LOW);
  }
  if(i==1){
    digitalWrite(led,HIGH);
    }
   if(i==2){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
    }
   if(i==3){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
    }
   if(i==4){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
    }
   if(i==5){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
    }
   if(i==6){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
    }
   if(i==7){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
    }
   if(i==8){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
    }
    if(i==9){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
    }
    if(i==10){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
    }
     if(i==11){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
    }
     if(i==12){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
    }
    if(i==13){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
    }
    if(i==14){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
    }
   if(i==15){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
    }
   if(i==16){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
    }
    if(i==17){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==18){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==19){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==20){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==21){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==22){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==23){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,LOW);
   digitalWrite(led_4,HIGH);
  }
  if(i==24){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==25){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==26){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==27){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,LOW);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==28){
   digitalWrite(led,LOW);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==29){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,LOW);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==30){
   digitalWrite(led,LOW);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==31){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
  }
  if(i==32){
   digitalWrite(led,HIGH);
   digitalWrite(led_1,HIGH);
   digitalWrite(led_2,HIGH);
   digitalWrite(led_3,HIGH);
   digitalWrite(led_4,HIGH);
   digitalWrite(led_5,HIGH);
  }
}
    
